Windows-amd64-32: turn _common_build into a file

diff --git a/Windows-amd64-32/_common_build b/Windows-amd64-32/_common_build
--- a/Windows-amd64-32/_common_build
+++ b/Windows-amd64-32/_common_build
@@ -1,1 +1,38 @@
-../Linux-i386-32/_common_build
+#!/bin/bash
+(
+  cd $librarydir
+  # clean target area
+  rm -rf ${workspacedir}/${library}
+
+  # build
+  if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir}
+  then
+    echo "error while building"
+    exit 1
+  fi
+
+  # install
+  if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} install
+  then
+    echo "error while installing"
+    exit 1
+  fi
+
+  # localdep
+  if $localdep; then
+    if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} localdep_${localdep_platform}
+    then
+      echo "error while adding dependencies locally"
+      exit 1
+    fi
+  fi
+
+  # clean build area
+  make $MAKEFLAGS clean
+
+  # create version-file
+  echo "$version" > ${workspacedir}/${library}/VERSION.txt
+
+  # copy
+  rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
+)
