build and install in separate statements some Makefiles need it apparently

diff --git a/Linux-i386-32/_common_build b/Linux-i386-32/_common_build
--- a/Linux-i386-32/_common_build
+++ b/Linux-i386-32/_common_build
@@ -5,12 +5,19 @@
   rm -rf ${workspacedir}/${library}
   
   # build
-  if ! make LIBRARY_NAME=${library} PD_PATH=${pddir} pkglibdir=${workspacedir} install
+  if ! make $MAKEFLAGS LIBRARY_NAME=${library} PD_PATH=${pddir} pkglibdir=${workspacedir}
   then
     echo "error while building"
     exit 1
   fi
   
+  # install
+  if ! make $MAKEFLAGS LIBRARY_NAME=${library} PD_PATH=${pddir} pkglibdir=${workspacedir} install
+  then
+    echo "error while installing"
+    exit 1
+  fi
+
   # clean build area
   make clean
   
diff --git a/Windows-i386-32/_common_build b/Windows-i386-32/_common_build
--- a/Windows-i386-32/_common_build
+++ b/Windows-i386-32/_common_build
@@ -6,6 +6,23 @@
   
   # build
   if ! ( make \
+        $MAKEFLAGS \
+        UNAME=MINGW \
+        CC=i686-w64-mingw32-gcc \
+        PD_PATH=${pddir} CFLAGS="" \
+	PD_INCLUDE=${pddir}/src \
+        LDFLAGS="-Wl,-l:pd.dll -Wl,--enable-auto-image-base" \
+        LIBS="-lpthread" \
+	pkglibdir=${workspacedir} \
+        )
+  then
+    echo "error while building"
+    exit 1
+  fi
+
+  # install
+  if ! ( make \
+        $MAKEFLAGS \
         UNAME=MINGW \
         CC=i686-w64-mingw32-gcc \
         PD_PATH=${pddir} CFLAGS="" \
@@ -15,7 +32,7 @@
 	pkglibdir=${workspacedir} \
 	install )
   then
-    echo "error while building"
+    echo "error while installing"
     exit 1
   fi
 
