add optional localdep target to _common_build

diff --git a/Linux-i386-32/_common_build b/Linux-i386-32/_common_build
--- a/Linux-i386-32/_common_build
+++ b/Linux-i386-32/_common_build
@@ -18,6 +18,15 @@
     exit 1
   fi
 
+  # localdep
+  if $localdep; then
+    if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} localdep_linux
+    then
+      echo "error while adding dependencies locally"
+      exit 1
+    fi
+  fi
+
   # clean build area
   make $MAKEFLAGS clean
 
